import { NutrientConstraint } from '../../types/constraints';

export const DEFAULT_CONSTRAINTS: NutrientConstraint[] = [
  // ── Macros ──────────────────────────────────────────────────────────────
  {
    nutrientKey: 'energyKcal',
    label: 'Energy',
    unit: 'kcal',
    min: 2000,
    max: 2000,
    defaultMin: 2000,
    defaultMax: 2000,
    fdaDaily: 2000,
    efsaDaily: 2000,
    enabled: true,
    group: 'Macros',
  },
  {
    nutrientKey: 'proteinG',
    label: 'Protein',
    unit: 'g',
    min: 50,
    max: 200,
    defaultMin: 50,
    defaultMax: 200,
    fdaDaily: 50,
    efsaDaily: 50,
    enabled: true,
    group: 'Macros',
  },
  {
    nutrientKey: 'fatG',
    label: 'Total Fat',
    unit: 'g',
    min: 44,
    max: 78,
    defaultMin: 44,
    defaultMax: 78,
    fdaDaily: 78,
    enabled: true,
    group: 'Macros',
  },
  {
    nutrientKey: 'saturatedFatG',
    label: 'Saturated Fat',
    unit: 'g',
    min: null,
    max: 20,
    defaultMin: null,
    defaultMax: 20,
    fdaDaily: 20,
    enabled: true,
    group: 'Macros',
  },
  {
    nutrientKey: 'carbohydratesG',
    label: 'Carbohydrates',
    unit: 'g',
    min: 225,
    max: 325,
    defaultMin: 225,
    defaultMax: 325,
    fdaDaily: 275,
    efsaDaily: 260,
    enabled: true,
    group: 'Macros',
  },
  {
    nutrientKey: 'fiberG',
    label: 'Dietary Fiber',
    unit: 'g',
    min: 28,
    max: null,
    defaultMin: 28,
    defaultMax: null,
    fdaDaily: 28,
    efsaDaily: 25,
    enabled: true,
    group: 'Macros',
  },
  {
    nutrientKey: 'sugarG',
    label: 'Added Sugars',
    unit: 'g',
    min: null,
    max: 50,
    defaultMin: null,
    defaultMax: 50,
    fdaDaily: 50,
    enabled: true,
    group: 'Macros',
  },
  // ── Minerals ────────────────────────────────────────────────────────────
  {
    nutrientKey: 'sodiumMg',
    label: 'Sodium',
    unit: 'mg',
    min: 500,
    max: 2300,
    defaultMin: 500,
    defaultMax: 2300,
    fdaDaily: 2300,
    efsaDaily: 2000,
    enabled: true,
    group: 'Minerals',
  },
  {
    nutrientKey: 'calciumMg',
    label: 'Calcium',
    unit: 'mg',
    min: 1000,
    max: 2500,
    defaultMin: 1000,
    defaultMax: 2500,
    fdaDaily: 1300,
    efsaDaily: 950,
    enabled: true,
    group: 'Minerals',
  },
  {
    nutrientKey: 'ironMg',
    label: 'Iron',
    unit: 'mg',
    min: 8,
    max: 45,
    defaultMin: 8,
    defaultMax: 45,
    fdaDaily: 18,
    efsaDaily: 16,
    enabled: true,
    group: 'Minerals',
  },
  {
    nutrientKey: 'potassiumMg',
    label: 'Potassium',
    unit: 'mg',
    min: 3400,
    max: null,
    defaultMin: 3400,
    defaultMax: null,
    fdaDaily: 4700,
    efsaDaily: 3500,
    enabled: true,
    group: 'Minerals',
  },
  {
    nutrientKey: 'magnesiumMg',
    label: 'Magnesium',
    unit: 'mg',
    min: 420,
    max: 700,
    defaultMin: 420,
    defaultMax: 700,
    fdaDaily: 420,
    efsaDaily: 350,
    enabled: false,
    group: 'Minerals',
  },
  {
    nutrientKey: 'zincMg',
    label: 'Zinc',
    unit: 'mg',
    min: 11,
    max: 40,
    defaultMin: 11,
    defaultMax: 40,
    fdaDaily: 11,
    efsaDaily: 9.4,
    enabled: false,
    group: 'Minerals',
  },
  // ── Vitamins ────────────────────────────────────────────────────────────
  {
    nutrientKey: 'vitaminCMg',
    label: 'Vitamin C',
    unit: 'mg',
    min: 90,
    max: 2000,
    defaultMin: 90,
    defaultMax: 2000,
    fdaDaily: 90,
    efsaDaily: 110,
    enabled: true,
    group: 'Vitamins',
  },
  {
    nutrientKey: 'vitaminDMcg',
    label: 'Vitamin D',
    unit: 'mcg',
    min: 20,
    max: 100,
    defaultMin: 20,
    defaultMax: 100,
    fdaDaily: 20,
    efsaDaily: 15,
    enabled: true,
    group: 'Vitamins',
  },
  {
    nutrientKey: 'vitaminB12Mcg',
    label: 'Vitamin B12',
    unit: 'mcg',
    min: 2.4,
    max: null,
    defaultMin: 2.4,
    defaultMax: null,
    fdaDaily: 2.4,
    efsaDaily: 4.0,
    enabled: true,
    group: 'Vitamins',
  },
  {
    nutrientKey: 'folateMcg',
    label: 'Folate (DFE)',
    unit: 'mcg',
    min: 400,
    max: 1000,
    defaultMin: 400,
    defaultMax: 1000,
    fdaDaily: 400,
    efsaDaily: 330,
    enabled: true,
    group: 'Vitamins',
  },
  // ── Fatty Acids ─────────────────────────────────────────────────────────
  {
    nutrientKey: 'omega3G',
    label: 'Omega-3',
    unit: 'g',
    min: 1.6,
    max: null,
    defaultMin: 1.6,
    defaultMax: null,
    fdaDaily: 1.6,
    efsaDaily: 2.0,
    enabled: false,
    group: 'Fatty Acids',
  },
];

export const CONSTRAINT_GROUPS = ['Macros', 'Minerals', 'Vitamins', 'Fatty Acids'] as const;
