// Auto-generated by scripts/seedFoods.ts on 2026-03-08
// Source: USDA FoodData Central — Foundation Foods
// Foods: 35 | Do not edit manually — re-run the script to refresh
import type { StaticFood } from './commonFoods';

export const GENERATED_FOODS: StaticFood[] = [
  {
    result: { id: '1105073', source: 'USDA' as const, name: "Bananas, overripe, raw", category: "Fruits and Fruit Juices", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.3,
    profile: {
      energyKcal: 85, proteinG: 0.73, fatG: 0.22, saturatedFatG: 0,
      carbohydratesG: 20.1, fiberG: 1.7, sugarG: 15.8, sodiumMg: 0,
      calciumMg: 0, ironMg: 0, potassiumMg: 0, vitaminCMg: 9.7,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 25,
      magnesiumMg: 0, zincMg: 0, omega3G: 0,
    },
  },
  {
    result: { id: '1105314', source: 'USDA' as const, name: "Bananas, ripe and slightly ripe, raw", category: "Fruits and Fruit Juices", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.3,
    profile: {
      energyKcal: 97, proteinG: 0.74, fatG: 0.29, saturatedFatG: 0,
      carbohydratesG: 23, fiberG: 1.7, sugarG: 15.8, sodiumMg: 0,
      calciumMg: 5, ironMg: 0, potassiumMg: 326, vitaminCMg: 12.3,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 14,
      magnesiumMg: 28, zincMg: 0.16, omega3G: 0,
    },
  },
  {
    result: { id: '321611', source: 'USDA' as const, name: "Beans, snap, green, canned, regular pack, drained solids", category: "Vegetables and Vegetable Products", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.2,
    profile: {
      energyKcal: 21, proteinG: 1.04, fatG: 0.39, saturatedFatG: 0,
      carbohydratesG: 4.11, fiberG: 0, sugarG: 1.29, sodiumMg: 282,
      calciumMg: 36, ironMg: 0.78, potassiumMg: 97, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 12.7, zincMg: 0.19, omega3G: 0,
    },
  },
  {
    result: { id: '335240', source: 'USDA' as const, name: "Bread, whole-wheat, commercially prepared", category: "Baked Products", dietaryTags: ['vegetarian','lactose-free'] },
    costPer100g: 0.25,
    profile: {
      energyKcal: 254, proteinG: 12.3, fatG: 3.55, saturatedFatG: 0.732,
      carbohydratesG: 43.1, fiberG: 6, sugarG: 4.41, sodiumMg: 450,
      calciumMg: 163, ironMg: 2.56, potassiumMg: 250, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 42,
      magnesiumMg: 76.6, zincMg: 1.76, omega3G: 0.139,
    },
  },
  {
    result: { id: '746764', source: 'USDA' as const, name: "Carrots, frozen, unprepared", category: "Vegetables and Vegetable Products", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.2,
    profile: {
      energyKcal: 37, proteinG: 0.81, fatG: 0.47, saturatedFatG: 0,
      carbohydratesG: 7.92, fiberG: 3.2, sugarG: 4.2, sodiumMg: 66,
      calciumMg: 33, ironMg: 0.43, potassiumMg: 210, vitaminCMg: 2.2,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 7,
      magnesiumMg: 10.8, zincMg: 0.28, omega3G: 0,
    },
  },
  {
    result: { id: '323793', source: 'USDA' as const, name: "Egg, white, dried", category: "Dairy and Egg Products", dietaryTags: ['vegetarian','gluten-free'] },
    costPer100g: 0.4,
    profile: {
      energyKcal: 376, proteinG: 79.9, fatG: 0.65, saturatedFatG: 0,
      carbohydratesG: 6.02, fiberG: 0, sugarG: 0, sodiumMg: 1250,
      calciumMg: 104, ironMg: 0, potassiumMg: 959, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 87.6, zincMg: 0.43, omega3G: 0,
    },
  },
  {
    result: { id: '323697', source: 'USDA' as const, name: "Egg, white, raw, frozen, pasteurized", category: "Dairy and Egg Products", dietaryTags: ['vegetarian','gluten-free'] },
    costPer100g: 0.4,
    profile: {
      energyKcal: 48, proteinG: 10.1, fatG: 0.16, saturatedFatG: 0,
      carbohydratesG: 0.74, fiberG: 0, sugarG: 0, sodiumMg: 144,
      calciumMg: 9, ironMg: 0.18, potassiumMg: 130, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 10.6, zincMg: 0.02, omega3G: 0,
    },
  },
  {
    result: { id: '323604', source: 'USDA' as const, name: "Egg, whole, raw, frozen, pasteurized", category: "Dairy and Egg Products", dietaryTags: ['vegetarian','gluten-free'] },
    costPer100g: 0.4,
    profile: {
      energyKcal: 150, proteinG: 12.3, fatG: 10.3, saturatedFatG: 0,
      carbohydratesG: 0.91, fiberG: 0, sugarG: 0, sodiumMg: 121,
      calciumMg: 55, ironMg: 1.77, potassiumMg: 117, vitaminCMg: 0,
      vitaminDMcg: 2.3, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 11.2, zincMg: 1.2, omega3G: 0,
    },
  },
  {
    result: { id: '329716', source: 'USDA' as const, name: "Egg, yolk, dried", category: "Dairy and Egg Products", dietaryTags: ['vegetarian','gluten-free'] },
    costPer100g: 0.4,
    profile: {
      energyKcal: 654, proteinG: 34.2, fatG: 55.5, saturatedFatG: 0,
      carbohydratesG: 1.07, fiberG: 0, sugarG: 0, sodiumMg: 149,
      calciumMg: 270, ironMg: 9.28, potassiumMg: 231, vitaminCMg: 0,
      vitaminDMcg: 15.7, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 26, zincMg: 7.11, omega3G: 0,
    },
  },
  {
    result: { id: '329596', source: 'USDA' as const, name: "Egg, yolk, raw, frozen, pasteurized", category: "Dairy and Egg Products", dietaryTags: ['vegetarian','gluten-free'] },
    costPer100g: 0.4,
    profile: {
      energyKcal: 296, proteinG: 15.6, fatG: 25.1, saturatedFatG: 0,
      carbohydratesG: 0.59, fiberG: 0, sugarG: 0, sodiumMg: 66,
      calciumMg: 119, ironMg: 4.13, potassiumMg: 102, vitaminCMg: 0,
      vitaminDMcg: 5.8, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 11.2, zincMg: 2.93, omega3G: 0,
    },
  },
  {
    result: { id: '748236', source: 'USDA' as const, name: "Eggs, Grade A, Large, egg yolk", category: "Dairy and Egg Products", dietaryTags: ['vegetarian','gluten-free'] },
    costPer100g: 0.4,
    profile: {
      energyKcal: 334, proteinG: 16.2, fatG: 28.8, saturatedFatG: 0,
      carbohydratesG: 1.02, fiberG: 0, sugarG: 0, sodiumMg: 0,
      calciumMg: 0, ironMg: 0, potassiumMg: 0, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 0, zincMg: 0, omega3G: 0,
    },
  },
  {
    result: { id: '790146', source: 'USDA' as const, name: "Flour, bread, white, enriched, unbleached", category: "Cereal Grains and Pasta", dietaryTags: ['vegetarian','vegan','lactose-free'] },
    costPer100g: 0.15,
    profile: {
      energyKcal: 363, proteinG: 14.3, fatG: 1.65, saturatedFatG: 0,
      carbohydratesG: 72.8, fiberG: 0, sugarG: 0, sodiumMg: 3,
      calciumMg: 19, ironMg: 5.55, potassiumMg: 127, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 145,
      magnesiumMg: 35.9, zincMg: 1.06, omega3G: 0,
    },
  },
  {
    result: { id: '790276', source: 'USDA' as const, name: "Flour, corn, yellow, fine meal, enriched", category: "Cereal Grains and Pasta", dietaryTags: ['vegetarian','vegan','lactose-free'] },
    costPer100g: 0.15,
    profile: {
      energyKcal: 364, proteinG: 6.2, fatG: 1.74, saturatedFatG: 0,
      carbohydratesG: 80.8, fiberG: 4.3, sugarG: 1.04, sodiumMg: 0,
      calciumMg: 0, ironMg: 4.44, potassiumMg: 144, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 155,
      magnesiumMg: 30.1, zincMg: 0.62, omega3G: 0,
    },
  },
  {
    result: { id: '1104913', source: 'USDA' as const, name: "Flour, pastry, unenriched, unbleached", category: "Cereal Grains and Pasta", dietaryTags: ['vegetarian','vegan','lactose-free'] },
    costPer100g: 0.15,
    profile: {
      energyKcal: 358, proteinG: 8.75, fatG: 1.64, saturatedFatG: 0,
      carbohydratesG: 77.2, fiberG: 0, sugarG: 0, sodiumMg: 1,
      calciumMg: 17, ironMg: 0.87, potassiumMg: 142, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 22.4, zincMg: 0.74, omega3G: 0,
    },
  },
  {
    result: { id: '1104812', source: 'USDA' as const, name: "Flour, rice, brown", category: "Cereal Grains and Pasta", dietaryTags: ['vegetarian','vegan','lactose-free'] },
    costPer100g: 0.15,
    profile: {
      energyKcal: 365.25, proteinG: 7.19, fatG: 3.85, saturatedFatG: 0,
      carbohydratesG: 75.5, fiberG: 0, sugarG: 0, sodiumMg: 1,
      calciumMg: 10, ironMg: 1.5, potassiumMg: 265, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 124, zincMg: 1.91, omega3G: 0,
    },
  },
  {
    result: { id: '1104867', source: 'USDA' as const, name: "Flour, rice, glutinous", category: "Cereal Grains and Pasta", dietaryTags: ['vegetarian','vegan','lactose-free'] },
    costPer100g: 0.15,
    profile: {
      energyKcal: 358, proteinG: 6.69, fatG: 1.16, saturatedFatG: 0,
      carbohydratesG: 80.1, fiberG: 0, sugarG: 0, sodiumMg: 6,
      calciumMg: 10, ironMg: 0.34, potassiumMg: 80, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 21.2, zincMg: 1.34, omega3G: 0,
    },
  },
  {
    result: { id: '790214', source: 'USDA' as const, name: "Flour, rice, white, unenriched", category: "Cereal Grains and Pasta", dietaryTags: ['vegetarian','vegan','lactose-free'] },
    costPer100g: 0.15,
    profile: {
      energyKcal: 359, proteinG: 6.94, fatG: 1.3, saturatedFatG: 0,
      carbohydratesG: 79.8, fiberG: 0.5, sugarG: 0, sodiumMg: 5,
      calciumMg: 6, ironMg: 0.22, potassiumMg: 75, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 16,
      magnesiumMg: 22.9, zincMg: 1.19, omega3G: 0,
    },
  },
  {
    result: { id: '1104705', source: 'USDA' as const, name: "Flour, soy, defatted", category: "Legumes and Legume Products", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.22,
    profile: {
      energyKcal: 366, proteinG: 51.1, fatG: 3.33, saturatedFatG: 0,
      carbohydratesG: 32.9, fiberG: 0, sugarG: 0, sodiumMg: 2,
      calciumMg: 338, ironMg: 7.34, potassiumMg: 2480, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 313, zincMg: 4.44, omega3G: 0,
    },
  },
  {
    result: { id: '1104766', source: 'USDA' as const, name: "Flour, soy, full-fat", category: "Legumes and Legume Products", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.22,
    profile: {
      energyKcal: 452, proteinG: 38.6, fatG: 20.7, saturatedFatG: 0,
      carbohydratesG: 27.9, fiberG: 0, sugarG: 0, sodiumMg: 2,
      calciumMg: 258, ironMg: 9.51, potassiumMg: 1860, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 254, zincMg: 3.75, omega3G: 0,
    },
  },
  {
    result: { id: '789890', source: 'USDA' as const, name: "Flour, wheat, all-purpose, enriched, bleached", category: "Cereal Grains and Pasta", dietaryTags: ['vegetarian','vegan','lactose-free'] },
    costPer100g: 0.15,
    profile: {
      energyKcal: 366, proteinG: 10.9, fatG: 1.48, saturatedFatG: 0,
      carbohydratesG: 77.3, fiberG: 0, sugarG: 0, sodiumMg: 2,
      calciumMg: 19, ironMg: 5.62, potassiumMg: 136, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 160,
      magnesiumMg: 26.7, zincMg: 0.72, omega3G: 0,
    },
  },
  {
    result: { id: '789951', source: 'USDA' as const, name: "Flour, wheat, all-purpose, enriched, unbleached", category: "Cereal Grains and Pasta", dietaryTags: ['vegetarian','vegan','lactose-free'] },
    costPer100g: 0.15,
    profile: {
      energyKcal: 358, proteinG: 13.1, fatG: 1.48, saturatedFatG: 0,
      carbohydratesG: 73.2, fiberG: 0, sugarG: 0, sodiumMg: 4,
      calciumMg: 21, ironMg: 5.41, potassiumMg: 135, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 159,
      magnesiumMg: 33.3, zincMg: 0.9, omega3G: 0,
    },
  },
  {
    result: { id: '790018', source: 'USDA' as const, name: "Flour, wheat, all-purpose, unenriched, unbleached", category: "Cereal Grains and Pasta", dietaryTags: ['vegetarian','vegan','lactose-free'] },
    costPer100g: 0.15,
    profile: {
      energyKcal: 362, proteinG: 12, fatG: 1.7, saturatedFatG: 0,
      carbohydratesG: 74.6, fiberG: 3, sugarG: 0, sodiumMg: 2,
      calciumMg: 22, ironMg: 1.18, potassiumMg: 150, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 23,
      magnesiumMg: 36.1, zincMg: 1.15, omega3G: 0,
    },
  },
  {
    result: { id: '790085', source: 'USDA' as const, name: "Flour, whole wheat, unenriched", category: "Cereal Grains and Pasta", dietaryTags: ['vegetarian','vegan','lactose-free'] },
    costPer100g: 0.15,
    profile: {
      energyKcal: 370, proteinG: 15.1, fatG: 2.73, saturatedFatG: 0,
      carbohydratesG: 71.2, fiberG: 10.6, sugarG: 0, sodiumMg: 3,
      calciumMg: 38, ironMg: 3.86, potassiumMg: 376, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 39,
      magnesiumMg: 136, zincMg: 3.24, omega3G: 0,
    },
  },
  {
    result: { id: '1104647', source: 'USDA' as const, name: "Garlic, raw", category: "Vegetables and Vegetable Products", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.2,
    profile: {
      energyKcal: 143, proteinG: 6.62, fatG: 0.38, saturatedFatG: 0,
      carbohydratesG: 28.2, fiberG: 2.7, sugarG: 0, sodiumMg: 0,
      calciumMg: 0, ironMg: 0, potassiumMg: 0, vitaminCMg: 10,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 0, zincMg: 0, omega3G: 0,
    },
  },
  {
    result: { id: '325287', source: 'USDA' as const, name: "Grapefruit juice, white, canned or bottled, unsweetened", category: "Fruits and Fruit Juices", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.3,
    profile: {
      energyKcal: 37, proteinG: 0.55, fatG: 0.7, saturatedFatG: 0,
      carbohydratesG: 7.59, fiberG: 0.2, sugarG: 7.72, sodiumMg: 1,
      calciumMg: 16, ironMg: 0.07, potassiumMg: 141, vitaminCMg: 39.4,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 12,
      magnesiumMg: 9.6, zincMg: 0.04, omega3G: 0,
    },
  },
  {
    result: { id: '326196', source: 'USDA' as const, name: "Kale, frozen, cooked, boiled, drained, without salt", category: "Vegetables and Vegetable Products", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.2,
    profile: {
      energyKcal: 36, proteinG: 2.94, fatG: 1.21, saturatedFatG: 0,
      carbohydratesG: 5.3, fiberG: 0, sugarG: 1.12, sodiumMg: 16,
      calciumMg: 150, ironMg: 0.84, potassiumMg: 144, vitaminCMg: 17.8,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 65,
      magnesiumMg: 25, zincMg: 0.27, omega3G: 0,
    },
  },
  {
    result: { id: '323505', source: 'USDA' as const, name: "Kale, raw", category: "Vegetables and Vegetable Products", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.2,
    profile: {
      energyKcal: 35, proteinG: 2.92, fatG: 1.49, saturatedFatG: 0,
      carbohydratesG: 4.42, fiberG: 4.1, sugarG: 0.8, sodiumMg: 53,
      calciumMg: 254, ironMg: 1.6, potassiumMg: 348, vitaminCMg: 93.4,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 62,
      magnesiumMg: 32.7, zincMg: 0.39, omega3G: 0,
    },
  },
  {
    result: { id: '747693', source: 'USDA' as const, name: "Ketchup, restaurant", category: "Vegetables and Vegetable Products", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.2,
    profile: {
      energyKcal: 117, proteinG: 1.11, fatG: 0.55, saturatedFatG: 0,
      carbohydratesG: 26.8, fiberG: 0, sugarG: 21.8, sodiumMg: 949,
      calciumMg: 14, ironMg: 0.43, potassiumMg: 249, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 13.5, zincMg: 0.16, omega3G: 0,
    },
  },
  {
    result: { id: '327046', source: 'USDA' as const, name: "Kiwifruit, green, raw", category: "Fruits and Fruit Juices", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.3,
    profile: {
      energyKcal: 58, proteinG: 1.06, fatG: 0.44, saturatedFatG: 0,
      carbohydratesG: 14, fiberG: 3, sugarG: 8.99, sodiumMg: 5,
      calciumMg: 35, ironMg: 0.24, potassiumMg: 198, vitaminCMg: 74.7,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 26,
      magnesiumMg: 15.7, zincMg: 0.14, omega3G: 0,
    },
  },
  {
    result: { id: '330458', source: 'USDA' as const, name: "Oil, coconut", category: "Fats and Oils", dietaryTags: [] },
    costPer100g: 0.65,
    profile: {
      energyKcal: 833, proteinG: 0, fatG: 99.1, saturatedFatG: 82.5,
      carbohydratesG: 0.84, fiberG: 0, sugarG: 0, sodiumMg: 0,
      calciumMg: 1, ironMg: 0.05, potassiumMg: 0, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 0, zincMg: 0.02, omega3G: 0.02,
    },
  },
  {
    result: { id: '790577', source: 'USDA' as const, name: "Onions, red, raw", category: "Vegetables and Vegetable Products", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.2,
    profile: {
      energyKcal: 44, proteinG: 0.94, fatG: 0.1, saturatedFatG: 0,
      carbohydratesG: 9.93, fiberG: 2.2, sugarG: 5.76, sodiumMg: 1,
      calciumMg: 17, ironMg: 0.24, potassiumMg: 197, vitaminCMg: 8.1,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 11.4, zincMg: 0.17, omega3G: 0,
    },
  },
  {
    result: { id: '1104962', source: 'USDA' as const, name: "Onions, white, raw", category: "Vegetables and Vegetable Products", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.2,
    profile: {
      energyKcal: 35, proteinG: 0.89, fatG: 0.13, saturatedFatG: 0,
      carbohydratesG: 7.68, fiberG: 1.2, sugarG: 5.76, sodiumMg: 2,
      calciumMg: 21, ironMg: 0.15, potassiumMg: 141, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 9.3, zincMg: 0.12, omega3G: 0,
    },
  },
  {
    result: { id: '790646', source: 'USDA' as const, name: "Onions, yellow, raw", category: "Vegetables and Vegetable Products", dietaryTags: ['vegetarian','vegan','lactose-free','gluten-free'] },
    costPer100g: 0.2,
    profile: {
      energyKcal: 38, proteinG: 0.83, fatG: 0.05, saturatedFatG: 0,
      carbohydratesG: 8.61, fiberG: 1.9, sugarG: 5.82, sodiumMg: 1,
      calciumMg: 15, ironMg: 0.28, potassiumMg: 182, vitaminCMg: 8.2,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 9, zincMg: 0.2, omega3G: 0,
    },
  },
  {
    result: { id: '746781', source: 'USDA' as const, name: "Sausage, pork, chorizo, link or ground, cooked, pan-fried", category: "Sausages and Luncheon Meats", dietaryTags: [] },
    costPer100g: 0.9,
    profile: {
      energyKcal: 346, proteinG: 19.3, fatG: 28.1, saturatedFatG: 9.45,
      carbohydratesG: 2.63, fiberG: 0, sugarG: 0, sodiumMg: 983,
      calciumMg: 37, ironMg: 2.34, potassiumMg: 435, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 1.21, folateMcg: 10,
      magnesiumMg: 30.1, zincMg: 2.19, omega3G: 0.192,
    },
  },
  {
    result: { id: '746784', source: 'USDA' as const, name: "Sugars, granulated", category: "Sweets", dietaryTags: [] },
    costPer100g: 0.7,
    profile: {
      energyKcal: 385, proteinG: 0, fatG: 0.32, saturatedFatG: 0,
      carbohydratesG: 99.6, fiberG: 0, sugarG: 99.8, sodiumMg: 1,
      calciumMg: 1, ironMg: 0.05, potassiumMg: 2, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 0.3, zincMg: 0.01, omega3G: 0,
    },
  }
];
