// Auto-generated by scripts/seedFoods.ts on 2026-03-08
// Source: USDA FoodData Central — Foundation Foods
// Foods: 30 | Do not edit manually — re-run the script to refresh
import type { StaticFood } from './commonFoods';

export const GENERATED_FOODS: StaticFood[] = [
  {
    result: { id: '1105073', source: 'USDA' as const, name: "Bananas, overripe, raw", category: {"id":9,"code":"0900","description":"Fruits and Fruit Juices"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 85, proteinG: 0.73, fatG: 0.22, saturatedFatG: 0,
      carbohydratesG: 20.1, fiberG: 1.7, sugarG: 15.8, sodiumMg: 0,
      calciumMg: 0, ironMg: 0, potassiumMg: 0, vitaminCMg: 9.7,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 25,
      magnesiumMg: 0, zincMg: 0, omega3G: 0,
    },
  },
  {
    result: { id: '321611', source: 'USDA' as const, name: "Beans, snap, green, canned, regular pack, drained solids", category: {"id":11,"code":"1100","description":"Vegetables and Vegetable Products"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 21, proteinG: 1.04, fatG: 0.39, saturatedFatG: 0,
      carbohydratesG: 4.11, fiberG: 0, sugarG: 1.29, sodiumMg: 282,
      calciumMg: 36, ironMg: 0.78, potassiumMg: 97, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 12.7, zincMg: 0.19, omega3G: 0,
    },
  },
  {
    result: { id: '331960', source: 'USDA' as const, name: "Chicken, broiler or fryers, breast, skinless, boneless, meat only, cooked, braised", category: {"id":5,"code":"0500","description":"Poultry Products"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 166, proteinG: 32.1, fatG: 3.24, saturatedFatG: 1.01,
      carbohydratesG: 0, fiberG: 0, sugarG: 0, sodiumMg: 47,
      calciumMg: 6, ironMg: 0.49, potassiumMg: 343, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0.2, folateMcg: 0,
      magnesiumMg: 32, zincMg: 0.96, omega3G: 0.037,
    },
  },
  {
    result: { id: '333008', source: 'USDA' as const, name: "Cookies, oatmeal, soft, with raisins", category: {"id":18,"code":"1800","description":"Baked Products"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 430, proteinG: 5.79, fatG: 14.3, saturatedFatG: 4.78,
      carbohydratesG: 69.6, fiberG: 3.3, sugarG: 34.8, sodiumMg: 314,
      calciumMg: 29, ironMg: 2.28, potassiumMg: 245, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 34,
      magnesiumMg: 32.4, zincMg: 0.62, omega3G: 0.637,
    },
  },
  {
    result: { id: '323697', source: 'USDA' as const, name: "Egg, white, raw, frozen, pasteurized", category: {"id":1,"code":"0100","description":"Dairy and Egg Products"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 48, proteinG: 10.1, fatG: 0.16, saturatedFatG: 0,
      carbohydratesG: 0.74, fiberG: 0, sugarG: 0, sodiumMg: 144,
      calciumMg: 9, ironMg: 0.18, potassiumMg: 130, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 10.6, zincMg: 0.02, omega3G: 0,
    },
  },
  {
    result: { id: '329596', source: 'USDA' as const, name: "Egg, yolk, raw, frozen, pasteurized", category: {"id":1,"code":"0100","description":"Dairy and Egg Products"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 296, proteinG: 15.6, fatG: 25.1, saturatedFatG: 0,
      carbohydratesG: 0.59, fiberG: 0, sugarG: 0, sodiumMg: 66,
      calciumMg: 119, ironMg: 4.13, potassiumMg: 102, vitaminCMg: 0,
      vitaminDMcg: 5.8, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 11.2, zincMg: 2.93, omega3G: 0,
    },
  },
  {
    result: { id: '790146', source: 'USDA' as const, name: "Flour, bread, white, enriched, unbleached", category: {"id":20,"code":"2000","description":"Cereal Grains and Pasta"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 363, proteinG: 14.3, fatG: 1.65, saturatedFatG: 0,
      carbohydratesG: 72.8, fiberG: 0, sugarG: 0, sodiumMg: 3,
      calciumMg: 19, ironMg: 5.55, potassiumMg: 127, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 145,
      magnesiumMg: 35.9, zincMg: 1.06, omega3G: 0,
    },
  },
  {
    result: { id: '790276', source: 'USDA' as const, name: "Flour, corn, yellow, fine meal, enriched", category: {"id":20,"code":"2000","description":"Cereal Grains and Pasta"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 364, proteinG: 6.2, fatG: 1.74, saturatedFatG: 0,
      carbohydratesG: 80.8, fiberG: 4.3, sugarG: 1.04, sodiumMg: 0,
      calciumMg: 0, ironMg: 4.44, potassiumMg: 144, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 155,
      magnesiumMg: 30.1, zincMg: 0.62, omega3G: 0,
    },
  },
  {
    result: { id: '1104913', source: 'USDA' as const, name: "Flour, pastry, unenriched, unbleached", category: {"id":20,"code":"2000","description":"Cereal Grains and Pasta"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 358, proteinG: 8.75, fatG: 1.64, saturatedFatG: 0,
      carbohydratesG: 77.2, fiberG: 0, sugarG: 0, sodiumMg: 1,
      calciumMg: 17, ironMg: 0.87, potassiumMg: 142, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 22.4, zincMg: 0.74, omega3G: 0,
    },
  },
  {
    result: { id: '1104812', source: 'USDA' as const, name: "Flour, rice, brown", category: {"id":20,"code":"2000","description":"Cereal Grains and Pasta"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 365.25, proteinG: 7.19, fatG: 3.85, saturatedFatG: 0,
      carbohydratesG: 75.5, fiberG: 0, sugarG: 0, sodiumMg: 1,
      calciumMg: 10, ironMg: 1.5, potassiumMg: 265, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 124, zincMg: 1.91, omega3G: 0,
    },
  },
  {
    result: { id: '1104867', source: 'USDA' as const, name: "Flour, rice, glutinous", category: {"id":20,"code":"2000","description":"Cereal Grains and Pasta"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 358, proteinG: 6.69, fatG: 1.16, saturatedFatG: 0,
      carbohydratesG: 80.1, fiberG: 0, sugarG: 0, sodiumMg: 6,
      calciumMg: 10, ironMg: 0.34, potassiumMg: 80, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 21.2, zincMg: 1.34, omega3G: 0,
    },
  },
  {
    result: { id: '790214', source: 'USDA' as const, name: "Flour, rice, white, unenriched", category: {"id":20,"code":"2000","description":"Cereal Grains and Pasta"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 359, proteinG: 6.94, fatG: 1.3, saturatedFatG: 0,
      carbohydratesG: 79.8, fiberG: 0.5, sugarG: 0, sodiumMg: 5,
      calciumMg: 6, ironMg: 0.22, potassiumMg: 75, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 16,
      magnesiumMg: 22.9, zincMg: 1.19, omega3G: 0,
    },
  },
  {
    result: { id: '1104705', source: 'USDA' as const, name: "Flour, soy, defatted", category: {"id":16,"code":"1600","description":"Legumes and Legume Products"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 366, proteinG: 51.1, fatG: 3.33, saturatedFatG: 0,
      carbohydratesG: 32.9, fiberG: 0, sugarG: 0, sodiumMg: 2,
      calciumMg: 338, ironMg: 7.34, potassiumMg: 2480, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 313, zincMg: 4.44, omega3G: 0,
    },
  },
  {
    result: { id: '1104766', source: 'USDA' as const, name: "Flour, soy, full-fat", category: {"id":16,"code":"1600","description":"Legumes and Legume Products"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 452, proteinG: 38.6, fatG: 20.7, saturatedFatG: 0,
      carbohydratesG: 27.9, fiberG: 0, sugarG: 0, sodiumMg: 2,
      calciumMg: 258, ironMg: 9.51, potassiumMg: 1860, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 254, zincMg: 3.75, omega3G: 0,
    },
  },
  {
    result: { id: '789890', source: 'USDA' as const, name: "Flour, wheat, all-purpose, enriched, bleached", category: {"id":20,"code":"2000","description":"Cereal Grains and Pasta"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 366, proteinG: 10.9, fatG: 1.48, saturatedFatG: 0,
      carbohydratesG: 77.3, fiberG: 0, sugarG: 0, sodiumMg: 2,
      calciumMg: 19, ironMg: 5.62, potassiumMg: 136, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 160,
      magnesiumMg: 26.7, zincMg: 0.72, omega3G: 0,
    },
  },
  {
    result: { id: '789951', source: 'USDA' as const, name: "Flour, wheat, all-purpose, enriched, unbleached", category: {"id":20,"code":"2000","description":"Cereal Grains and Pasta"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 358, proteinG: 13.1, fatG: 1.48, saturatedFatG: 0,
      carbohydratesG: 73.2, fiberG: 0, sugarG: 0, sodiumMg: 4,
      calciumMg: 21, ironMg: 5.41, potassiumMg: 135, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 159,
      magnesiumMg: 33.3, zincMg: 0.9, omega3G: 0,
    },
  },
  {
    result: { id: '790018', source: 'USDA' as const, name: "Flour, wheat, all-purpose, unenriched, unbleached", category: {"id":20,"code":"2000","description":"Cereal Grains and Pasta"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 362, proteinG: 12, fatG: 1.7, saturatedFatG: 0,
      carbohydratesG: 74.6, fiberG: 3, sugarG: 0, sodiumMg: 2,
      calciumMg: 22, ironMg: 1.18, potassiumMg: 150, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 23,
      magnesiumMg: 36.1, zincMg: 1.15, omega3G: 0,
    },
  },
  {
    result: { id: '790085', source: 'USDA' as const, name: "Flour, whole wheat, unenriched", category: {"id":20,"code":"2000","description":"Cereal Grains and Pasta"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 370, proteinG: 15.1, fatG: 2.73, saturatedFatG: 0,
      carbohydratesG: 71.2, fiberG: 10.6, sugarG: 0, sodiumMg: 3,
      calciumMg: 38, ironMg: 3.86, potassiumMg: 376, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 39,
      magnesiumMg: 136, zincMg: 3.24, omega3G: 0,
    },
  },
  {
    result: { id: '1104647', source: 'USDA' as const, name: "Garlic, raw", category: {"id":11,"code":"1100","description":"Vegetables and Vegetable Products"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 143, proteinG: 6.62, fatG: 0.38, saturatedFatG: 0,
      carbohydratesG: 28.2, fiberG: 2.7, sugarG: 0, sodiumMg: 0,
      calciumMg: 0, ironMg: 0, potassiumMg: 0, vitaminCMg: 10,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 0, zincMg: 0, omega3G: 0,
    },
  },
  {
    result: { id: '325287', source: 'USDA' as const, name: "Grapefruit juice, white, canned or bottled, unsweetened", category: {"id":9,"code":"0900","description":"Fruits and Fruit Juices"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 37, proteinG: 0.55, fatG: 0.7, saturatedFatG: 0,
      carbohydratesG: 7.59, fiberG: 0.2, sugarG: 7.72, sodiumMg: 1,
      calciumMg: 16, ironMg: 0.07, potassiumMg: 141, vitaminCMg: 39.4,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 12,
      magnesiumMg: 9.6, zincMg: 0.04, omega3G: 0,
    },
  },
  {
    result: { id: '326196', source: 'USDA' as const, name: "Kale, frozen, cooked, boiled, drained, without salt", category: {"id":11,"code":"1100","description":"Vegetables and Vegetable Products"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 36, proteinG: 2.94, fatG: 1.21, saturatedFatG: 0,
      carbohydratesG: 5.3, fiberG: 0, sugarG: 1.12, sodiumMg: 16,
      calciumMg: 150, ironMg: 0.84, potassiumMg: 144, vitaminCMg: 17.8,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 65,
      magnesiumMg: 25, zincMg: 0.27, omega3G: 0,
    },
  },
  {
    result: { id: '323505', source: 'USDA' as const, name: "Kale, raw", category: {"id":11,"code":"1100","description":"Vegetables and Vegetable Products"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 35, proteinG: 2.92, fatG: 1.49, saturatedFatG: 0,
      carbohydratesG: 4.42, fiberG: 4.1, sugarG: 0.8, sodiumMg: 53,
      calciumMg: 254, ironMg: 1.6, potassiumMg: 348, vitaminCMg: 93.4,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 62,
      magnesiumMg: 32.7, zincMg: 0.39, omega3G: 0,
    },
  },
  {
    result: { id: '747693', source: 'USDA' as const, name: "Ketchup, restaurant", category: {"id":11,"code":"1100","description":"Vegetables and Vegetable Products"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 117, proteinG: 1.11, fatG: 0.55, saturatedFatG: 0,
      carbohydratesG: 26.8, fiberG: 0, sugarG: 21.8, sodiumMg: 949,
      calciumMg: 14, ironMg: 0.43, potassiumMg: 249, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 13.5, zincMg: 0.16, omega3G: 0,
    },
  },
  {
    result: { id: '327046', source: 'USDA' as const, name: "Kiwifruit, green, raw", category: {"id":9,"code":"0900","description":"Fruits and Fruit Juices"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 58, proteinG: 1.06, fatG: 0.44, saturatedFatG: 0,
      carbohydratesG: 14, fiberG: 3, sugarG: 8.99, sodiumMg: 5,
      calciumMg: 35, ironMg: 0.24, potassiumMg: 198, vitaminCMg: 74.7,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 26,
      magnesiumMg: 15.7, zincMg: 0.14, omega3G: 0,
    },
  },
  {
    result: { id: '330458', source: 'USDA' as const, name: "Oil, coconut", category: {"id":4,"code":"0400","description":"Fats and Oils"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 833, proteinG: 0, fatG: 99.1, saturatedFatG: 82.5,
      carbohydratesG: 0.84, fiberG: 0, sugarG: 0, sodiumMg: 0,
      calciumMg: 1, ironMg: 0.05, potassiumMg: 0, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 0, zincMg: 0.02, omega3G: 0.02,
    },
  },
  {
    result: { id: '790577', source: 'USDA' as const, name: "Onions, red, raw", category: {"id":11,"code":"1100","description":"Vegetables and Vegetable Products"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 44, proteinG: 0.94, fatG: 0.1, saturatedFatG: 0,
      carbohydratesG: 9.93, fiberG: 2.2, sugarG: 5.76, sodiumMg: 1,
      calciumMg: 17, ironMg: 0.24, potassiumMg: 197, vitaminCMg: 8.1,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 11.4, zincMg: 0.17, omega3G: 0,
    },
  },
  {
    result: { id: '1104962', source: 'USDA' as const, name: "Onions, white, raw", category: {"id":11,"code":"1100","description":"Vegetables and Vegetable Products"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 35, proteinG: 0.89, fatG: 0.13, saturatedFatG: 0,
      carbohydratesG: 7.68, fiberG: 1.2, sugarG: 5.76, sodiumMg: 2,
      calciumMg: 21, ironMg: 0.15, potassiumMg: 141, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 9.3, zincMg: 0.12, omega3G: 0,
    },
  },
  {
    result: { id: '790646', source: 'USDA' as const, name: "Onions, yellow, raw", category: {"id":11,"code":"1100","description":"Vegetables and Vegetable Products"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 38, proteinG: 0.83, fatG: 0.05, saturatedFatG: 0,
      carbohydratesG: 8.61, fiberG: 1.9, sugarG: 5.82, sodiumMg: 1,
      calciumMg: 15, ironMg: 0.28, potassiumMg: 182, vitaminCMg: 8.2,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 9, zincMg: 0.2, omega3G: 0,
    },
  },
  {
    result: { id: '746781', source: 'USDA' as const, name: "Sausage, pork, chorizo, link or ground, cooked, pan-fried", category: {"id":7,"code":"0700","description":"Sausages and Luncheon Meats"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 346, proteinG: 19.3, fatG: 28.1, saturatedFatG: 9.45,
      carbohydratesG: 2.63, fiberG: 0, sugarG: 0, sodiumMg: 983,
      calciumMg: 37, ironMg: 2.34, potassiumMg: 435, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 1.21, folateMcg: 10,
      magnesiumMg: 30.1, zincMg: 2.19, omega3G: 0.192,
    },
  },
  {
    result: { id: '746784', source: 'USDA' as const, name: "Sugars, granulated", category: {"id":19,"code":"1900","description":"Sweets"}, dietaryTags: [] },
    costPer100g: 0.5,
    profile: {
      energyKcal: 385, proteinG: 0, fatG: 0.32, saturatedFatG: 0,
      carbohydratesG: 99.6, fiberG: 0, sugarG: 99.8, sodiumMg: 1,
      calciumMg: 1, ironMg: 0.05, potassiumMg: 2, vitaminCMg: 0,
      vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0,
      magnesiumMg: 0.3, zincMg: 0.01, omega3G: 0,
    },
  }
];
