// Auto-generated by scripts/seedFoods.ts — do not edit manually
// Run `npm run seed:foods` with a USDA API key to populate this file.
import type { StaticFood } from './commonFoods';

export const GENERATED_FOODS: StaticFood[] = [];
